/**
 * React Native 平台环境变量加载器
 * 支持 react-native-config 或 process.env
 */

export interface EnvConfig {
  INTERACTION_IDLE_TIMEOUT?: string;
  INTERACTION_FADE_TRANSITION_DURATION?: string;
  INTERACTION_TOUCH_HOLD_THRESHOLD?: string;
  INTERACTION_ECHO_DISPLAY_DURATION?: string;
  INTERACTION_TOUCH_DEBOUNCE_THRESHOLD?: string;
  INTERACTION_PLAYBACK_START_DELAY?: string;
  INTERACTION_ECHO_HIDE_DELAY?: string;
  INTERACTION_MAX_RETRY_COUNT?: string;
  INTERACTION_AUDIO_SESSION_CLEANUP_DELAY?: string;
  INTERACTION_AUDIO_SESSION_CLEANUP_DELAY_FIRST?: string;
  INTERACTION_ERROR_RECOVERY_DELAY?: string;
  INTERACTION_ENABLE_STATE_TRANSITION_LOGGING?: string;
  INTERACTION_ENABLE_STATE_TRANSITION_VALIDATION?: string;
  INTERACTION_MIN_RECORDING_DURATION_FOR_ECHO?: string;
  METRO_DEFAULT_PORT?: string;
  METRO_DEFAULT_HOST?: string;
  METRO_BUNDLE_ROOT?: string;
  METRO_BUNDLE_NAME?: string;
  METRO_BUNDLE_EXTENSION?: string;
}

export function loadEnvConfig(): EnvConfig {
  // 尝试使用 react-native-config
  try {
    // @ts-expect-error - react-native-config 可能未安装，动态 require
    const Config = require('react-native-config');
    if (Config) {
      return {
        INTERACTION_IDLE_TIMEOUT: Config.INTERACTION_IDLE_TIMEOUT,
        INTERACTION_FADE_TRANSITION_DURATION: Config.INTERACTION_FADE_TRANSITION_DURATION,
        INTERACTION_TOUCH_HOLD_THRESHOLD: Config.INTERACTION_TOUCH_HOLD_THRESHOLD,
        INTERACTION_ECHO_DISPLAY_DURATION: Config.INTERACTION_ECHO_DISPLAY_DURATION,
        INTERACTION_TOUCH_DEBOUNCE_THRESHOLD: Config.INTERACTION_TOUCH_DEBOUNCE_THRESHOLD,
        INTERACTION_PLAYBACK_START_DELAY: Config.INTERACTION_PLAYBACK_START_DELAY,
        INTERACTION_ECHO_HIDE_DELAY: Config.INTERACTION_ECHO_HIDE_DELAY,
        INTERACTION_MAX_RETRY_COUNT: Config.INTERACTION_MAX_RETRY_COUNT,
        INTERACTION_AUDIO_SESSION_CLEANUP_DELAY: Config.INTERACTION_AUDIO_SESSION_CLEANUP_DELAY,
        INTERACTION_AUDIO_SESSION_CLEANUP_DELAY_FIRST: Config.INTERACTION_AUDIO_SESSION_CLEANUP_DELAY_FIRST,
        INTERACTION_ERROR_RECOVERY_DELAY: Config.INTERACTION_ERROR_RECOVERY_DELAY,
        INTERACTION_ENABLE_STATE_TRANSITION_LOGGING: Config.INTERACTION_ENABLE_STATE_TRANSITION_LOGGING,
        INTERACTION_ENABLE_STATE_TRANSITION_VALIDATION: Config.INTERACTION_ENABLE_STATE_TRANSITION_VALIDATION,
        INTERACTION_MIN_RECORDING_DURATION_FOR_ECHO: Config.INTERACTION_MIN_RECORDING_DURATION_FOR_ECHO,
        METRO_DEFAULT_PORT: Config.METRO_DEFAULT_PORT,
        METRO_DEFAULT_HOST: Config.METRO_DEFAULT_HOST,
        METRO_BUNDLE_ROOT: Config.METRO_BUNDLE_ROOT,
        METRO_BUNDLE_NAME: Config.METRO_BUNDLE_NAME,
        METRO_BUNDLE_EXTENSION: Config.METRO_BUNDLE_EXTENSION,
      };
    }
  } catch (e) {
    // react-native-config 未安装，继续使用 process.env
  }
  
  // 回退到 process.env
  if (typeof process !== 'undefined' && process.env) {
    return {
      INTERACTION_IDLE_TIMEOUT: process.env.INTERACTION_IDLE_TIMEOUT,
      INTERACTION_FADE_TRANSITION_DURATION: process.env.INTERACTION_FADE_TRANSITION_DURATION,
      INTERACTION_TOUCH_HOLD_THRESHOLD: process.env.INTERACTION_TOUCH_HOLD_THRESHOLD,
      INTERACTION_ECHO_DISPLAY_DURATION: process.env.INTERACTION_ECHO_DISPLAY_DURATION,
      INTERACTION_TOUCH_DEBOUNCE_THRESHOLD: process.env.INTERACTION_TOUCH_DEBOUNCE_THRESHOLD,
      INTERACTION_PLAYBACK_START_DELAY: process.env.INTERACTION_PLAYBACK_START_DELAY,
      INTERACTION_ECHO_HIDE_DELAY: process.env.INTERACTION_ECHO_HIDE_DELAY,
      INTERACTION_MAX_RETRY_COUNT: process.env.INTERACTION_MAX_RETRY_COUNT,
      INTERACTION_AUDIO_SESSION_CLEANUP_DELAY: process.env.INTERACTION_AUDIO_SESSION_CLEANUP_DELAY,
      INTERACTION_AUDIO_SESSION_CLEANUP_DELAY_FIRST: process.env.INTERACTION_AUDIO_SESSION_CLEANUP_DELAY_FIRST,
      INTERACTION_ERROR_RECOVERY_DELAY: process.env.INTERACTION_ERROR_RECOVERY_DELAY,
      INTERACTION_ENABLE_STATE_TRANSITION_LOGGING: process.env.INTERACTION_ENABLE_STATE_TRANSITION_LOGGING,
      INTERACTION_ENABLE_STATE_TRANSITION_VALIDATION: process.env.INTERACTION_ENABLE_STATE_TRANSITION_VALIDATION,
      INTERACTION_MIN_RECORDING_DURATION_FOR_ECHO: process.env.INTERACTION_MIN_RECORDING_DURATION_FOR_ECHO,
      METRO_DEFAULT_PORT: process.env.METRO_DEFAULT_PORT,
      METRO_DEFAULT_HOST: process.env.METRO_DEFAULT_HOST,
      METRO_BUNDLE_ROOT: process.env.METRO_BUNDLE_ROOT,
      METRO_BUNDLE_NAME: process.env.METRO_BUNDLE_NAME,
      METRO_BUNDLE_EXTENSION: process.env.METRO_BUNDLE_EXTENSION,
    };
  }
  
  return {};
}
