/**
 * Taro 平台环境变量加载器
 * 使用 process.env
 */

export interface EnvConfig {
  INTERACTION_IDLE_TIMEOUT?: string;
  INTERACTION_FADE_TRANSITION_DURATION?: string;
  INTERACTION_TOUCH_HOLD_THRESHOLD?: string;
  INTERACTION_ECHO_DISPLAY_DURATION?: string;
  APP_LOG_LEVEL?: string;
  METRO_DEFAULT_PORT?: string;
  METRO_DEFAULT_HOST?: string;
  METRO_BUNDLE_ROOT?: string;
  METRO_BUNDLE_NAME?: string;
  METRO_BUNDLE_EXTENSION?: string;
}

export function loadEnvConfig(): EnvConfig {
  // Taro 使用 process.env
  if (typeof process !== 'undefined' && process.env) {
    return {
      INTERACTION_IDLE_TIMEOUT: process.env.INTERACTION_IDLE_TIMEOUT || process.env.TARO_APP_INTERACTION_IDLE_TIMEOUT,
      INTERACTION_FADE_TRANSITION_DURATION: process.env.INTERACTION_FADE_TRANSITION_DURATION || process.env.TARO_APP_INTERACTION_FADE_TRANSITION_DURATION,
      INTERACTION_TOUCH_HOLD_THRESHOLD: process.env.INTERACTION_TOUCH_HOLD_THRESHOLD || process.env.TARO_APP_INTERACTION_TOUCH_HOLD_THRESHOLD,
      INTERACTION_ECHO_DISPLAY_DURATION: process.env.INTERACTION_ECHO_DISPLAY_DURATION || process.env.TARO_APP_INTERACTION_ECHO_DISPLAY_DURATION,
      APP_LOG_LEVEL: process.env.APP_LOG_LEVEL || process.env.TARO_APP_LOG_LEVEL,
      METRO_DEFAULT_PORT: process.env.METRO_DEFAULT_PORT || process.env.TARO_APP_METRO_DEFAULT_PORT,
      METRO_DEFAULT_HOST: process.env.METRO_DEFAULT_HOST || process.env.TARO_APP_METRO_DEFAULT_HOST,
      METRO_BUNDLE_ROOT: process.env.METRO_BUNDLE_ROOT || process.env.TARO_APP_METRO_BUNDLE_ROOT,
      METRO_BUNDLE_NAME: process.env.METRO_BUNDLE_NAME || process.env.TARO_APP_METRO_BUNDLE_NAME,
      METRO_BUNDLE_EXTENSION: process.env.METRO_BUNDLE_EXTENSION || process.env.TARO_APP_METRO_BUNDLE_EXTENSION,
    };
  }
  
  return {};
}
