/**
 * Web 平台环境变量加载器
 * 从 window.__ENV__（由 Vite 插件注入）或 process.env 读取环境变量
 * 避免使用 import.meta.env 以确保 Metro 可以正常解析此文件
 */

export interface EnvConfig {
  INTERACTION_IDLE_TIMEOUT?: string;
  INTERACTION_FADE_TRANSITION_DURATION?: string;
  INTERACTION_TOUCH_HOLD_THRESHOLD?: string;
  INTERACTION_ECHO_DISPLAY_DURATION?: string;
  INTERACTION_TOUCH_DEBOUNCE_THRESHOLD?: string;
  INTERACTION_PLAYBACK_START_DELAY?: string;
  INTERACTION_ECHO_HIDE_DELAY?: string;
  INTERACTION_MAX_RETRY_COUNT?: string;
  INTERACTION_AUDIO_SESSION_CLEANUP_DELAY?: string;
  INTERACTION_AUDIO_SESSION_CLEANUP_DELAY_FIRST?: string;
  INTERACTION_ERROR_RECOVERY_DELAY?: string;
  INTERACTION_ENABLE_STATE_TRANSITION_LOGGING?: string;
  INTERACTION_ENABLE_STATE_TRANSITION_VALIDATION?: string;
  INTERACTION_MIN_RECORDING_DURATION_FOR_ECHO?: string;
  APP_LOG_LEVEL?: string;
  METRO_DEFAULT_PORT?: string;
  METRO_DEFAULT_HOST?: string;
  METRO_BUNDLE_ROOT?: string;
  METRO_BUNDLE_NAME?: string;
  METRO_BUNDLE_EXTENSION?: string;
}

export function loadEnvConfig(): EnvConfig {
  // 在 Web 环境中，优先检查 window.__ENV__（由 Vite 插件注入）
  if (typeof window !== 'undefined' && (window as any).__ENV__) {
    const windowEnv = (window as any).__ENV__;
    return {
      INTERACTION_IDLE_TIMEOUT: windowEnv.INTERACTION_IDLE_TIMEOUT || windowEnv.VITE_INTERACTION_IDLE_TIMEOUT,
      INTERACTION_FADE_TRANSITION_DURATION: windowEnv.INTERACTION_FADE_TRANSITION_DURATION || windowEnv.VITE_INTERACTION_FADE_TRANSITION_DURATION,
      INTERACTION_TOUCH_HOLD_THRESHOLD: windowEnv.INTERACTION_TOUCH_HOLD_THRESHOLD || windowEnv.VITE_INTERACTION_TOUCH_HOLD_THRESHOLD,
      INTERACTION_ECHO_DISPLAY_DURATION: windowEnv.INTERACTION_ECHO_DISPLAY_DURATION || windowEnv.VITE_INTERACTION_ECHO_DISPLAY_DURATION,
      APP_LOG_LEVEL: windowEnv.APP_LOG_LEVEL || windowEnv.VITE_APP_LOG_LEVEL,
      METRO_DEFAULT_PORT: windowEnv.METRO_DEFAULT_PORT || windowEnv.VITE_METRO_DEFAULT_PORT,
      METRO_DEFAULT_HOST: windowEnv.METRO_DEFAULT_HOST || windowEnv.VITE_METRO_DEFAULT_HOST,
      METRO_BUNDLE_ROOT: windowEnv.METRO_BUNDLE_ROOT || windowEnv.VITE_METRO_BUNDLE_ROOT,
      METRO_BUNDLE_NAME: windowEnv.METRO_BUNDLE_NAME || windowEnv.VITE_METRO_BUNDLE_NAME,
      METRO_BUNDLE_EXTENSION: windowEnv.METRO_BUNDLE_EXTENSION || windowEnv.VITE_METRO_BUNDLE_EXTENSION,
    };
  }
  
  // 回退到 process.env（Node.js 环境或构建时）
  // 这样可以避免 Metro 解析 import.meta 语法的问题
  if (typeof process !== 'undefined' && process.env) {
    const env = process.env;
    return {
      INTERACTION_IDLE_TIMEOUT: env.INTERACTION_IDLE_TIMEOUT || env.VITE_INTERACTION_IDLE_TIMEOUT,
      INTERACTION_FADE_TRANSITION_DURATION: env.INTERACTION_FADE_TRANSITION_DURATION || env.VITE_INTERACTION_FADE_TRANSITION_DURATION,
      INTERACTION_TOUCH_HOLD_THRESHOLD: env.INTERACTION_TOUCH_HOLD_THRESHOLD || env.VITE_INTERACTION_TOUCH_HOLD_THRESHOLD,
      INTERACTION_ECHO_DISPLAY_DURATION: env.INTERACTION_ECHO_DISPLAY_DURATION || env.VITE_INTERACTION_ECHO_DISPLAY_DURATION,
      APP_LOG_LEVEL: env.APP_LOG_LEVEL || env.VITE_APP_LOG_LEVEL,
      METRO_DEFAULT_PORT: env.METRO_DEFAULT_PORT || env.VITE_METRO_DEFAULT_PORT,
      METRO_DEFAULT_HOST: env.METRO_DEFAULT_HOST || env.VITE_METRO_DEFAULT_HOST,
      METRO_BUNDLE_ROOT: env.METRO_BUNDLE_ROOT || env.VITE_METRO_BUNDLE_ROOT,
      METRO_BUNDLE_NAME: env.METRO_BUNDLE_NAME || env.VITE_METRO_BUNDLE_NAME,
      METRO_BUNDLE_EXTENSION: env.METRO_BUNDLE_EXTENSION || env.VITE_METRO_BUNDLE_EXTENSION,
    };
  }
  
  return {};
}
